language: generic
sudo: required
services:
    - docker
addons:
    apt:
        update: true
        packages:
            - gnupg2
            - pass

before_install:
    - docker build -t deskmonkey/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true deskmonkey/react-test npm test

after_success:
    - docker build -t deskmonkey/multi-client ./client 
    - docker build -t deskmonkey/multi-nginx ./nginx
    - docker build -t deskmonkey/multi-server ./server
    - docker build -t deskmonkey/multi-worker ./worker

#Login to docker CLI
    - mkdir ~/.docker
    - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

#Push to docker hub
    - docker push deskmonkey/multi-client
    - docker push deskmonkey/multi-nginx
    - docker push deskmonkey/multi-server
    - docker push deskmonkey/multi-worker